import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "./(root)/_components/Navbar";

const getRoboto = Roboto({
  subsets: ['latin'],
  variable: "--roboto",
  weight: ['400', '500', '700']
})
export const metadata = {
  title: "Fryzjer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pl">
      <body
        className={`${getRoboto} antialiased`}
      >
        <div>
          <Navbar />
        </div>
        {children}
      </body>
    </html>
  );
}
